---
- name: variable playbook test
  hosts: localhost

  vars: 
     var_1: awesome
     var_2: ansible is
     var_3: "{{ var_2 }} {{ var_1 }}"

  tasks:
  - name: print out the third variable
    ansible.builtin.debug:
      msg: "{{ var_3 }}"
 
  - name: print out some facts
    ansible.builtin.debug:
      msg: The default IPv4 address of {{ ansible_hostname }} is {{ ansible_default_ipv4.address }}